// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class Exam
{
    public string ExamId { get; set; }

    public string ExamName { get; set; }

    public string Type { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string SemesterId { get; set; }

    public bool? Status { get; set; }

    public virtual Semester Semester { get; set; }

    public virtual ICollection<Slot> Slots { get; set; } = new List<Slot>();

    public virtual ICollection<Subject> Subjects { get; set; } = new List<Subject>();
}