// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class FormSlot
{
    public string FormSlotId { get; set; }

    public string FormId { get; set; }

    public string SlotId { get; set; }

    public bool? Status { get; set; }

    public virtual RegistrationForm Form { get; set; }

    public virtual Slot Slot { get; set; }
}