// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class GroupRoom
{
    public string GroupRoomId { get; set; }

    public string GroupId { get; set; }

    public string RoomId { get; set; }

    public virtual Group Group { get; set; }

    public virtual Room Room { get; set; }
}