// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ExamProctoringManagement.Data.Models;

public partial class Room
{
    public string RoomId { get; set; }

    public string RoomName { get; set; }

    [JsonIgnore]
    public virtual ICollection<GroupRoom> GroupRooms { get; set; } = new List<GroupRoom>();
    [JsonIgnore]
    public virtual ICollection<SlotReference> SlotReferences { get; set; } = new List<SlotReference>();
}