// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class Semester
{
    public string SemesterId { get; set; }

    public string SemesterName { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}