// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class SlotRoomSubject
{
    public string SlotRoomSubjectId { get; set; }

    public string SlotReferenceId { get; set; }

    public string SubjectId { get; set; }

    public bool? Status { get; set; }

    public virtual SlotReference SlotReference { get; set; }

    public virtual Subject Subject { get; set; }
}