// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExamProctoringManagement.Data.Models;

public partial class Subject
{
    public string SubjectId { get; set; }

    public string SubjectName { get; set; }

    public string ExamId { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<SlotRoomSubject> SlotRoomSubjects { get; set; } = new List<SlotRoomSubject>();
}