# Tên của workflow
name: Build and deploy ASP.Net Core app to Azure Web App - ExamProctoringManagement

# Kích hoạt workflow khi có thay đổi trên nhánh main
on:
  push:
    branches:
      - main
    paths:
      - 'ExamProctoringManagement/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước checkout mã nguồn
      - uses: actions/checkout@v4

      # Thiết lập .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Build project với dotnet, chỉ rõ đường dẫn file .sln
      - name: Build with dotnet
        run: dotnet build ExamProctoringManagement/ExamProctoringManagement.sln --configuration Release

      # Publish project với dotnet, chỉ rõ đường dẫn file .sln
      - name: dotnet publish
        run: dotnet publish ExamProctoringManagement/ExamProctoringManagement.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Upload artifact để deploy
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download artifact từ job build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      # Deploy lên Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ExamProctoringManagement'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7769A7C9C3094696A5DB2E00A5CEDF98 }}
